# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jP0hfA5O4j1AounpfAvq69V5YAC7RT8Z
"""

# channel.py
import torch

def power_normalize(x, eps=1e-8):
    # x: (B, C, H, W)
    p = x.pow(2).mean(dim=(1, 2, 3), keepdim=True).clamp_min(eps)
    return x / torch.sqrt(p)

def awgn(x, snr_db):
    snr_lin = 10 ** (snr_db / 10)
    noise_var = 1.0 / snr_lin
    noise = torch.randn_like(x) * torch.sqrt(
        torch.tensor(noise_var, device=x.device, dtype=x.dtype)
    )
    return x + noise