# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jP0hfA5O4j1AounpfAvq69V5YAC7RT8Z
"""

# metrics.py
import torch
import torch.nn.functional as F

def psnr(x, xhat, eps=1e-8):
    mse = F.mse_loss(xhat, x, reduction="mean").clamp_min(eps)
    return 10.0 * torch.log10(1.0 / mse)  # assuming x in [0,1]