# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jP0hfA5O4j1AounpfAvq69V5YAC7RT8Z
"""

# models.py
import torch.nn as nn
from channel import power_normalize, awgn

class Encoder(nn.Module):
    def __init__(self, latent_ch=8):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(3, 32, 3, stride=2, padding=1), nn.ReLU(),
            nn.Conv2d(32, 64, 3, stride=2, padding=1), nn.ReLU(),
            nn.Conv2d(64, latent_ch, 3, stride=1, padding=1),
        )
    def forward(self, x):
        return self.net(x)

class Decoder(nn.Module):
    def __init__(self, latent_ch=8):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(latent_ch, 64, 3, padding=1), nn.ReLU(),
            nn.Upsample(scale_factor=2, mode="nearest"),
            nn.Conv2d(64, 32, 3, padding=1), nn.ReLU(),
            nn.Upsample(scale_factor=2, mode="nearest"),
            nn.Conv2d(32, 3, 3, padding=1),
            nn.Sigmoid(),
        )
    def forward(self, z):
        return self.net(z)

class DeepJSCC(nn.Module):
    def __init__(self, latent_ch=8):
        super().__init__()
        self.enc = Encoder(latent_ch)
        self.dec = Decoder(latent_ch)

    def forward(self, x, snr_db):
        z = self.enc(x)
        z = power_normalize(z)
        y = awgn(z, snr_db)
        xhat = self.dec(y)
        return xhat